### ISSUE TITLE
Error message when running homebridge

### ISSUE THREAD

**Issue by neo2k1ca** [timcharper/homebridge-opensprinkler#3]
Homebridge finds the sprinkler and zones but then I get the following error when running homebridge. 

[2018-6-29 11:24:51] Loaded config.json with 0 accessories and 4 platforms.
[2018-6-29 11:24:51] ---
[2018-6-29 11:24:51] Loaded plugin: homebridge-ademco
[2018-6-29 11:24:51] Registering platform 'homebridge-ademco.Ademco'
[2018-6-29 11:24:51] ---
[2018-6-29 11:24:51] Loaded plugin: homebridge-alexa
[2018-6-29 11:24:51] Registering platform 'homebridge-alexa.Alexa'
[2018-6-29 11:24:51] ---
[2018-6-29 11:24:51] Loaded plugin: homebridge-envisakit
[2018-6-29 11:24:51] Registering accessory 'homebridge-envisakit.Envisakit'
[2018-6-29 11:24:51] ---
[2018-6-29 11:24:51] Loaded plugin: homebridge-vera
VeraLink initializing
[2018-6-29 11:24:51] Registering platform 'homebridge-veralink.Vera'
[2018-6-29 11:24:51] ---
[2018-6-29 11:24:52] Loaded plugin: homebridge-opensprinkler
[2018-6-29 11:24:52] Registering platform 'homebridge-opensprinkler.OpenSprinkler'
[2018-6-29 11:24:52] ---
[2018-6-29 11:24:52] Loading 4 platforms...
[2018-6-29 11:24:52] [Vera] Initializing Vera platform...
[2018-6-29 11:24:52] [Ademco] Initializing Ademco platform...
[2018-6-29 11:24:52] [OpenSprinkler] Initializing OpenSprinkler platform...
[2018-6-29 11:24:52] [Alexa] Initializing Alexa platform...
[2018-6-29 11:24:52] [Ademco] [Ademco] is online.
[2018-6-29 11:24:52] [OpenSprinkler] Station names:
[2018-6-29 11:24:52] [OpenSprinkler] [ 'Rear Left',
  'Rear Right',
  'Rear Middle',
  'Side right',
  'Front Right',
  'Front Left',
  'S07',
  'S08' ]
[2018-6-29 11:24:52] [OpenSprinkler] error while polling: TypeError: promise.finally is not a function
    at Promise (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:9:22)
    at new Promise (<anonymous>)
    at withTimeoutCancellation (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:4:12)
    at System.poll (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:34:18)
    at new System (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:25:12)
    at openSprinklerApi.getStatus.then (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:62:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-6-29 11:24:52] [OpenSprinkler] TypeError: done.finally is not a function
    at System.poll (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:54:19)
    at new System (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:25:12)
    at openSprinklerApi.getStatus.then (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:62:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:102534) UnhandledPromiseRejectionWarning: TypeError: done.finally is not a function
    at System.poll (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:54:19)
    at new System (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:25:12)
    at openSprinklerApi.getStatus.then (/usr/local/lib/node_modules/homebridge-opensprinkler/lib/system.js:62:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:102534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:102534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Process Device 29: Garage
Process Device 31: Front Door
Process Device 32: Backyard light
Process Device 42: Garage Door
Process Device 43: Porch Light
Process Device 119: TV Lamp
Process Device 120: Server Plug
Process Device 121: Basement TV
Process Device 126: Guest Bath Plug
Process Device 127: Nursery Plug
Process Device 133: Sump Pump
Process Device 195: OpenSprinkler Controller
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Garage'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Front Door'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Backyard light'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Garage Door'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Porch Light'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'TV Lamp'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Server Plug'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Basement TV'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Guest Bath Plug'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Nursery Plug'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'Sump Pump'...
[2018-6-29 11:24:52] [Vera] Initializing platform accessory 'OpenSprinkler Controller'...
[2018-6-29 11:25:17] [OpenSprinkler] cancelling promise because it is too slow

**Comment by neo2k1ca** [comment]
using nodejs/node of v8.11.3

Homebridge works if i take out the opensprinkler component.

**Comment by neo2k1ca** [comment]
Just saw the closed issue. Had to upgrade to node/nodejs 10.1.0
